import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
"""
Takes the csv as generated by the test data and cleans it for usage in rolldownconverter.py
"""
def clean(file, windspeed = 0):
    data = pd.read_csv(file)
    # Calculate the average measured velocity
    data['average_velocity'] = data[['vehicle_velocity_right','vehicle_velocity_left']].mean(axis = 1)
    # The first ~50 data points will always be useless
    data = data.truncate(50)
    # Drop all data from when the throttle is on
    index = data.throttle.ne(0).idxmin()
    data = data.truncate(index)
    # Drop all the columns where we don't have velocity data
    data = data.dropna(subset = ['average_velocity'])
    # Drop data near 0
    index = data[data['average_velocity'] < 400].index
    data = data.drop(index)
    # Correct time offset
    data['time'] = data['Time Offset [ms]'] - data['Time Offset [ms]'].iloc[0] 
    # Convert to seconds
    data['time'] = data['time'] / 1000
    # Adjust and convert to ms
    data['average_velocity'] = data['average_velocity'] / 100
    # Drop unnecessary data
    data = data[['time', 'average_velocity']]
    return data
